---

# Dataset metadata
default_dataset: &default_dataset
    type: PythonDataset
    delim: "\t"
    buffer_size: 40000
    shuffle: True
    map_tables:
        word2id:
            path: word.cvt.dict
        word2id_emb:
            path: word_emb.cvt.dict
        relation2id: 
            path: relation.cvt.dict
        entity2id: 
            path: entity.cvt.dict

    slots:
        idx:
            index: 0
            type: value
            value_type: int32
        word: &default_slot
            index: 1
            type: sequence
            delim: " "
            map_table: word2id
            max_length: 46
            pad: 0
        word_emb:
            map_table: word2id_emb
            << : *default_slot
        relation:
            index: 2
#            type: value
            max_length: 3
            map_table: relation2id
            << : *default_slot
        entity:
            index: 3
            max_length: 2
#            type: value
            map_table: entity2id
            << : *default_slot

pred_dataset: &pred_dataset
    type: PythonDataset
    delim: "\t"
    buffer_size: 40000
    shuffle: True
    map_tables:
        word2id:
            path: word.cvt.dict
        word2id_emb:
            path: word_emb.cvt.dict
        relation2id: 
            path: relation.cvt.dict
        entity2id: 
            path: entity.cvt.dict

    slots: 
        idx:
            index: 0
            type: value
            value_type: int32
        word:
            index: 1
            << : *default_slot
        word_emb:
            map_table: word2id_emb
            << : *default_slot
#        relation:
#            index: 2
#            type: value
#            map_table: relation2id
#            << : *default_slot
        entity:
            index: 3
#            type: value
            map_table: entity2id

train_dataset: &train_dataset
    path: data/EMNLP.train.cvt.new
    << : *default_dataset

dev_dataset: &dev_dataset
    shuffle: False
    path: data/EMNLP.dev.cvt.new
    << : *default_dataset

test_dataset: &test_dataset
    shuffle: False
    path: data/EMNLP.dev.cvt.new
    << : *default_dataset

predict_dataset: &predict_dataset
    shuffle: False
    path: data/EMNLP.test.cvt.new
    << : *pred_dataset

# logging:
#     file: results/cvt_semantic_parsing/logging.out
#     level: 3

# Model config
model:
    model_name: DependencyModel
    
    # Data
    max_length: 60
    max_char: 31
    relation_max_len: 12
    
    char_size: 144
    trigram_size: 5356
    vocab_size: 18382
    vocab_size_emb: 15564
    relation_size: 1229

    # Word-level encoder
    use_word_pretrain_emb: True
    word_emb_finetune: True
    word2vec_emb: 'embedding.cvt.300d'
    word2gram_emb: 'word2gram_emb_cvt.npy'
    relation2word: 'relation2word_cvt.npy'
    relation2word_emb: 'relation2word_emb_cvt.npy'
    word_emb_size: 300
    use_rnn: True
    hidden_size: 300
    word_aggregation: end # max, mean, end (only for rnn), attention

    # Char-level encoder
    word2char: 'word2char_cvt.npy'
    word2gram: 'word2gram_cvt.npy'
    relation2char: 'relation2char_cvt.npy'
    relation2gram: 'relation2gram_cvt.npy'
    char_emb_size: 300
    encoder: trigram # trigram or CNN
    region_radius: 1 # only for trigram
    groups: 1 # only for CNN
    filters: 300 # only for CNN
    kernel_size: 1 # only for CNN
    use_rnn_char: False
    hidden_size_char: 300 # only for rnn
    aggregation: max # max, mean, attention

    # Combination
    use_highway: False
    
    # Projection to semantic space
    layer_num: 0
    
    semantic_size: 500
    dropout_rate: 0.1
    negative_samples: 100
    gamma: 5
    
    # Training
    batch_size: 100
    optimizer: Adam
    learning_rate: 0.02
    use_clip_by_norm: True
    decay_step: 270
    decay_rate: 0.95

# Estimator
estimator:
    type: PythonEstimator
    train_dataset: *train_dataset
    eval_datasets:
        # - *train_dataset
        - *dev_dataset
        # - *test_dataset
    eval_to_file: True
    eval_op_path: results/cvt_semantic_parsing/eval.output
    # infer_dataset: *predict_dataset
    # infer_op_path: results/cvt_semantic_parsing/infer.output

    batch_size: 100
    max_epochs: 40

    word2id: word.cvt.dict
    word2id_emb: word_emb.cvt.dict
    relation2id: relation.cvt.dict
    entity2id: entity.cvt.dict
    checkpoint_dir: results/cvt_semantic_parsing/checkpoint

    model_name: semantic_parsing_model
    # save_checkpoints_steps: 2000
    eval_interval_epochs: 100
#    eval_interval_steps: 100
    max_training_steps: 40000
    log_every_n_steps: 20
    tolerance: 5
    skip_eval_save: False