---

# Dataset metadata
default_dataset: &default_dataset
    type: PythonDataset
    delim: "\t"
    buffer_size: 40000
    shuffle: True
    map_tables:
        word2id:
            path: word.dict
        word2id_emb:
            path: word_emb.dict
        word2id_train:
            path: word_train.dict
        relation2id: 
            path: relation.dict
        entity2id: 
            path: entity.dict
        entity2id: 
            path: entity.dict
        comb2id: 
            path: comb.dict

    slots: 
        idx:
            index: 0
            type: value
            value_type: int32
        word: &default_slot
            index: 1
            type: sequence
            delim: " "
            map_table: word2id
            max_length: 56
            pad: 0
        word_emb:
            index: 4
            map_table: word2id_emb
            << : *default_slot
        word_train:
            map_table: word2id_train
            << : *default_slot
#        relation:
#            index: 2
#            max_length: 3
#            map_table: relation2id
#            << : *default_slot
        relation:
            index: 2
            type: value
            map_table: comb2id
            << : *default_slot
        entity:
            index: 3
            max_length: 2
            map_table: entity2id
            << : *default_slot
        typ:
            index: 5
            type: value
            value_type: int32

pred_dataset: &pred_dataset
    type: PythonDataset
    delim: "\t"
    buffer_size: 40000
    shuffle: True
    map_tables:
        word2id:
            path: word.dict
        word2id_emb:
            path: word_emb.dict
        word2id_train:
            path: word_train.dict
        relation2id: 
            path: relation.dict

    slots: 
        idx:
            index: 0
            type: value
            value_type: int32
        word:
            index: 1
            << : *default_slot
        word_emb:
            index: 3
            map_table: word2id_emb
            << : *default_slot
        word_train:
            map_table: word2id_train
            << : *default_slot
#        relation:
#            index: 2
#            type: value
#            map_table: relation2id
#            << : *default_slot
        entity:
            index: 4
            type: value
            map_table: entity2id

train_dataset: &train_dataset
    path: data/EMNLP.train.new
    << : *default_dataset

dev_dataset: &dev_dataset
    shuffle: False
    path: data/EMNLP.dev.new
    << : *default_dataset

test_dataset: &test_dataset
    shuffle: False
    path: data/EMNLP.dev.new
    << : *default_dataset

#predict_dataset: &predict_dataset
#    shuffle: False
#    path: data/EMNLP.test.new
#    << : *pred_dataset

# logging:
#     file: results/semantic_parsing/logging.out
#     level: 3

# Model config
model:
    model_name: DependencyModel
    
    # Data
    max_length: 56
    max_char: 32
    relation_max_len: 12
    
    char_size: 148
    trigram_size: 6293
    vocab_size: 21332
    vocab_size_emb: 16908
    vocab_size_train: 7782
    relation_size: 1562
    comb_size: 436
    single_size: 1229

    # Word-level encoder
    use_word_pretrain_emb: True
    word_emb_finetune: True
    word2vec_emb: 'embedding.300d'
    word2gram_emb: 'word2gram_emb.npy'
    relation2word: 'relation2word.npy'
    relation2word_emb: 'relation2word_emb.npy'
    relation2word_train: 'relation2word_train.npy'
    word_emb_size: 300
    use_rnn: True
    hidden_size: 300
    word_aggregation: max # max, mean, end (only for rnn), attention

    # Char-level encoder
    word2char: 'word2char.npy'
    word2gram: 'word2gram.npy'
    relation2char: 'relation2char.npy'
    relation2gram: 'relation2gram.npy'
    char_emb_size: 500
    encoder: trigram # trigram or CNN
    region_radius: 1 # only for trigram
    groups: 1 # only for CNN
    filters: # only for CNN
        - 50
        - 50
        - 50
    kernel_size: # only for CNN
        - 3
        - 5
        - 7
    use_rnn_char: False
    hidden_size_char: 100 # only for rnn
    aggregation: max # max, mean, attention

    # Combination
    use_highway: False
    
    # Projection to semantic space
    layer_num: 0
    semantic_size: 1000
    gamma: 5
    comb2relation: 'comb2relation.npy'
    
    # Training
    batch_size: 100
    optimizer: Adam
    learning_rate: 0.02
    dropout_rate: 0.05
#    negative_samples: 100
    use_clip_by_norm: True
    decay_step: 309
    decay_rate: 0.9

# Estimator
estimator:
    type: PythonEstimator
    train_dataset: *train_dataset
    eval_datasets:
        # - *train_dataset
        - *dev_dataset
        # - *test_dataset
    eval_to_file: True
    eval_op_path: results/semantic_parsing/eval.output
    # infer_dataset: *predict_dataset
    # infer_op_path: results/semantic_parsing/infer.output

    batch_size: 100
    max_epochs: 40

    word2id: word.dict
    word2id_emb: word_emb.dict
    relation2id: relation.dict
    comb2id: comb.dict
    entity2id: entity.dict
    checkpoint_dir: results/semantic_parsing/checkpoint

    model_name: semantic_parsing_model
    # save_checkpoints_steps: 2000
    eval_interval_epochs: 100
#    eval_interval_steps: 100
    max_training_steps: 40000
    log_every_n_steps: 20
    tolerance: 5
    skip_eval_save: False